
version: 2

models:
    - name: my_first_dbt_model
      columns:
          - name: id
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      columns:
          - name: id
            tests:
                - unique
                - not_null
    - name: source_demo
      columns:
          - name: CUSTOMER_ID
            tests:
                - not_null
    - name: test5
      columns:
          - name: status
            tests:
               - accepted_values:
                  values: ['delivered', 'shipped', 'completed', 'returned']